name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install frontend dependencies and run ESLint
        run: |
          cd frontend
          npm install
          npm run lint

      - name: Install backend dependencies and run ESLint
        run: |
          cd backend
          npm install
          npm run lint
