name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        working-directory: ./backend

      - name: Install dependencies for backend
        run: npm install
        working-directory: ./backend

      - name: Lint and auto-fix backend
        run: npm run lint -- --fix
        working-directory: ./backend

  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        working-directory: ./frontend

      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./frontend

      - name: Lint and auto-fix frontend
        run: npm run lint -- --fix
        working-directory: ./frontend
